name: RPA de banco # nome do teste

# trigger (gatilho)
on: 
  push: # o que vai ativar esse gatilho
    branches: ["main"] # e qual a branch que vai gerar o gatilho (["*"] todas as branches)

# define o que ele vai verificar
jobs:
  build:
    runs-on: ubuntu-latest

    # passos a serem executados ex:(rodar o requirements, rodar o python, rodar o banco)
    steps:
      - uses: actions/checkout@v2 # entra na pasta do meu projeto

      - name: Configurar ambiente para o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt

      - name: Configurar variáveis de ambiente
        run: |
          echo "DB_HOST1=${{ secrets.DB_HOST1 }}" >> $GITHUB_ENV
          echo "DB_DATABASE1=${{ secrets.DB_DATABASE1 }}" >> $GITHUB_ENV
          echo "DB_USER1=${{ secrets.DB_USER1 }}" >> $GITHUB_ENV
          echo "DB_PASSWORD1=${{ secrets.DB_PASSWORD1 }}" >> $GITHUB_ENV
          echo "DB_PORT1=${{ secrets.DB_PORT1 }}" >> $GITHUB_ENV
          echo "DB_DATABASE2=${{ secrets.DB_DATABASE2 }}" >> $GITHUB_ENV
  
      - name: Verificar variáveis de ambiente
        run: |
          echo "DB_HOST1=${{ env.DB_HOST1 }}"
          echo "DB_DATABASE1=${{ env.DB_DATABASE1 }}"
          echo "DB_USER1=${{ env.DB_USER1 }}"
          echo "DB_PASSWORD1=${{ env.DB_PASSWORD1 }}"
          echo "DB_PORT1=${{ env.DB_PORT1 }}"
          echo "DB_DATABASE2=${{ env.DB_DATABASE2 }}"

      - name: Run covarage python
        run: |
          coverage run transformador.py

      - name: Resultados
        run: coverage report

      - name: Deploy no EC2 -AWS
        run: |
          echo "Conectando no EC2"
          echo "${{secrets.AWS_CHAVE_PIPELINE_AWS_PEM}}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@"${{secrets.chave_ubuntu}}" "
          cd Aws_pipeline/;git pull;cd python_flask/;./iniciarApp.sh"      